
name: Daily Discord Export

on:
  schedule:
    - cron: "0 13 * * *"  # Runs every day at 8AM EST
  workflow_dispatch:

jobs:
  autopilot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pybaseball requests

      - name: Run Autopilot Export
        run: |
          python autopilot.py
